### ISSUE TITLE
Repeat failure

### ISSUE THREAD

**Issue by shymuel** [njuaplusplus/Elijah#1]
First of all, thank you for developing and sharing the code for the paper  [Elijah: Eliminating Backdoors Injected in Diffusion Models via Distribution Shift]. I was trying to use your code to reproduce the performance metrics reported in the paper, but unfortunately I was not able to achieve the same results.

For BadDiff, I tested trigger box-14 and stoptign-14 with poisoning rates of 0.1 and 0.3, respectively. Unlike in the paper, only when the poison rate is 0.3 and the trigger is box14 can the elijah_helper run to get a set of images that are all targets. The test model is downloaded from huggingface.

In particular, I would like to ask:
1. Is there any updated code or parameter Settings that have not been updated on GitHub?
2. Are there specific environmental or dependency requirements that have a significant impact on performance?
3. Do you have any additional suggestions or guidelines for reproducing the paper results?

I appreciate any help or guidance you can provide and look forward to hearing from you.

Thank you!

**Comment by njuaplusplus** [comment]
Thank you for your interest in our paper. We used the default environment provided by BadDiff, but I guess a slight different environment should not be a big problem.

For the stop sign case, are you referring to the example provided in our [script](https://github.com/njuaplusplus/Elijah/blob/main/BadDiffusion/run_example.sh)? 

Could you share some samples of the set of images produced? We don't need all the images to be the target to detect or remove the backdoor. As you can see in Figure 14 in [our appendix](https://arxiv.org/pdf/2312.00050.pdf), there are some non-target images generated with the inverted trigger as well.


Best,
Shengwei
