### ISSUE TITLE
Is the elijah_helper.py file specifically designed for BadDiffusion?

### ISSUE THREAD

**Issue by echomyz** [njuaplusplus/Elijah#2]
Hello, thank you very much for your work! I have some questions about elijah_helper.py. I want to know if it is specifically designed for BadDiffusion, and if I can replace "res_DDPM-CIFAR10-32_CIFAR10_ep50_c1.0_p0.1_STOP_SIGN_14-HAT" with the ckpt file of the attacked stable diffusion model, and then check for the presence of backdoors.

**Comment by njuaplusplus** [comment]
Thank you for the question. The currently released code is only for DDPM. The overall idea for NCSN and LDM is almost the same. For stable diffusion models, it should be similar to LDM. We will release the code for NCSN and LDM soon.

**Comment by echomyz** [comment]
Thank you for your answer! I would like to ask whether the detection method of backdoor attack is the same for attacks using image patches as triggers and attacks using words in text as triggers, and are the codes similar?

**Comment by njuaplusplus** [comment]
From our preliminary results, they are different.  Image-based triggers and text-based ones are injected in different ways. So the detection methods should be different too.
